name: Kotlin and Java tests

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: openjdk:21-bookworm

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-cache-${{ runner.os }}-v1
          restore-keys: |
            gradle-cache-${{ runner.os }}-

      - name: Build
        run: ./gradlew clean build --no-daemon --stacktrace -x test

      - name: Test
        run: ./gradlew test --no-daemon --stacktrace
