name: Kotlin and Java tests

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: openjdk:21-bookworm

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: List Gradle files
        run: |
          echo "Gradle files found:"
          find . -name "*.gradle*" -o -name "gradle-wrapper.properties"

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle', '**/build.gradle.kts', '**/settings.gradle', '**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build
        run: ./gradlew clean build --no-daemon --stacktrace -x test

      - name: Test
        run: ./gradlew test --no-daemon --stacktrace
